docker-compose-yaml: docker-compose.yml

project: k8s-drupal-example-1

# Lagoon K8s endpoints.
endpoint: ssh-lagoon-k8s-kubernetes.ch.amazee.io:32185
ssh: ssh-lagoon-k8s-kubernetes.ch.amazee.io:32185
api: https://api-lagoon-k8s-kubernetes.ch.amazee.io

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF database is empty
        command: |
            if tables=$(drush sqlq "show tables;") && [ -z "$tables" ]; then
                # no drupal installed, we install drupal from scratch
                ./vendor/bin/sake dev/build
            fi
        service: cli
        shell: bash
    - run:
        name: Show dev tasks
        command: ./vendor/bin/sake dev/
        service: cli
